config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, class_name: 'Account::User'

  namespace :admin do
    root 'home#index', as: :root

    namespace :account do
      root 'home#index', as: :root
      resources :users
    end
  end

  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/' do
    api_version module: 'V1', path: { value: 'v1' } do
      root 'home#index', as: :root
      namespace :account do
        resources :sessions, only: [:create, :destroy]
        resources :registrations, only: [:create]
        resources :users, only: [:show, :update]
      end
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
    end

    api_version module: 'V2', path: { value: 'v2' }, default: true do
      root 'home#index', as: :root
      namespace :account do
        resources :sessions, only: [:create, :destroy]
        resources :registrations, only: [:create]
        resources :users, only: [:show, :update]
      end
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/views/layouts/admin/_breadcrumb_title.html.erb
<h1 class="section-title">Usuários</h1>

<ol class="breadcrumb">
  <li><%= link_to 'Home', admin_root_path %></li>
  <li><%= link_to 'Contas', admin_account_root_path %></li>
  <li><%= link_to 'Usuários', admin_account_users_path %></li>
  <% if content_for?(:page_title) %>
    <li class="active"><%= yield :page_title %></li>
  <% end %>
</ol>

app/views/layouts/admin/_footer.html.erb
<footer class="admin-footer">
  <div class="container-fluid">
    <ul class="list-unstyled list-inline">
      <li>
        <%= link_to 'http://codde.io', title: 'Codde', target: 'blank' do %>
          <%= image_tag('codde.io.png', style: 'height:27px') %>
        <% end %>
      </li>
      <li class="pull-right for-support">
        <%= link_to 'mailto:suporte@codde.io', target: 'blank' do %>
          <div><%= pmd_icon('mail') %></div>
          <small>suporte@codde.io</small>
        <% end %>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/admin/_left_sidebar.html.erb
<aside class="pmd-sidebar pmd-sidebar-open sidebar-default pmd-sidebar-slide-push pmd-sidebar-left bg-fill-darkblue sidebar-with-icons" role="navigation">
  <ul class="nav pmd-sidebar-nav">
    <li class="dropdown pmd-dropdown pmd-user-info visible-xs visible-md visible-sm visible-lg">
      <a aria-expanded="false" data-toggle="dropdown" class="btn-user dropdown-toggle media" data-sidebar="true" aria-expandedhref="javascript:void(0);">
        <div class="media-left">
          <%= pmd_icon('perm_identity', class: 'pmd-md') %>
        </div>
        <div class="media-body media-middle"><%= current_user.full_name || current_user.email %></div>
        <div class="media-right media-middle"><i class="dic-more-vert dic"></i></div>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      </ul>
    </li>

    <li>
      <%= link_to admin_root_path do %>
        <%= pmd_icon('dashboard', class: 'media-left media-middle') %>
        <span class="media-body">Dashboard</span>
      <% end %>
    </li>

    <li class="dropdown pmd-dropdown open">
      <a href="#" data-toggle="dropdown" class="btn-user dropdown-toggle media">
        <%= pmd_icon('people', class: 'media-left media-middle') %>
        <span class="media-body">Contas</span>
        <div class="media-right media-bottom"><i class="dic-more-vert dic"></i></div>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Dashboard', admin_account_root_path, class: 'active' %></li>
        <li><%= link_to 'Usuários', admin_account_users_path %></li>
      </ul>
    </li>
  </ul>
</aside>

app/views/layouts/admin/_navbar.html.erb
<!--Start Nav bar -->
<nav class="navbar navbar-inverse navbar-fixed-top pmd-navbar pmd-z-depth">
  <div class="container-fluid">
    <div class="pmd-navbar-right-icon pull-right navigation">
      <!-- Notifications -->
      <div class="dropdown notification icons pmd-dropdown">
        <a href="javascript:void(0)" title="Notification" class="dropdown-toggle pmd-ripple-effect"  data-toggle="dropdown" role="button" aria-expanded="true">
          <div data-badge="3" class="material-icons md-light pmd-sm pmd-badge  pmd-badge-overlap">notifications_none</div>
        </a>
        <div class="dropdown-menu dropdown-menu-right pmd-card pmd-card-default pmd-z-depth" role="menu">
          <!-- Card header -->
          <div class="pmd-card-title">
            <div class="media-body media-middle">
              <a href="notifications.html" class="pull-right">3 new notifications</a>
              <h3 class="pmd-card-title-text">Notifications</h3>
            </div>
          </div>
          <!-- Notifications list -->
          <ul class="list-group pmd-list-avatar pmd-card-list">
            <li class="list-group-item" style="display:none">
              <p class="notification-blank">
                <span class="dic dic-notifications-none"></span>
                <span>You don´t have any notifications</span>
              </p>
            </li>
            <li class="list-group-item unread">
              <a href="javascript:void(0)">
                <div class="media-left">
                  <span class="avatar-list-img40x40">
                    <i class="material-icons pmd-md">perm_identity</i>
                  </span>
                </div>
                <div class="media-body">
                  <span class="list-group-item-heading"><span>Prathit</span> posted a new challanegs</span>
                  <span class="list-group-item-text">5 Minutes ago</span>
                </div>
              </a>
            </li>
            <li class="list-group-item">
              <a href="javascript:void(0)">
                <div class="media-left">
                  <span class="avatar-list-img40x40">
                    <i class="material-icons pmd-md">perm_identity</i>
                  </span>
                </div>
                <div class="media-body">
                  <span class="list-group-item-heading"><span>Keel</span> Cloned 2 challenges.</span>
                  <span class="list-group-item-text">15 Minutes ago</span>
                </div>
              </a>
            </li>
            <li class="list-group-item unread">
              <a href="javascript:void(0)">
                <div class="media-left">
                  <span class="avatar-list-img40x40">
                    <i class="material-icons pmd-md">perm_identity</i>
                  </span>
                </div>
                <div class="media-body">
                  <span class="list-group-item-heading"><span>John</span> posted new collection.</span>
                  <span class="list-group-item-text">25 Minutes ago</span>
                </div>
              </a>
            </li>
            <li class="list-group-item unread">
              <a href="javascript:void(0)">
                <div class="media-left">
                  <span class="avatar-list-img40x40">
                    <i class="material-icons pmd-md">perm_identity</i>
                  </span>
                </div>
                <div class="media-body">
                  <span class="list-group-item-heading"><span>Valerii</span> Shared 5 collection.</span>
                  <span class="list-group-item-text">30 Minutes ago</span>
                </div>
              </a>
            </li>
          </ul>
          <!-- End notifications list -->
        </div>
      </div>
      <!-- End notifications -->
    </div>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a href="javascript:void(0);" class="btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect pull-left margin-r8 pmd-sidebar-toggle">
        <i class="material-icons">menu</i>
      </a>

      <%= link_to image_tag('logo.png'), admin_root_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>
<!--End Nav bar -->

<div class="pmd-sidebar-overlay"></div>

app/views/layouts/admin/application.html.erb
<% content_for :head_title do %>
  <%= admin_page_title yield :page_title %>
<% end %>

<% content_for :navbar do %>
  <%= render 'layouts/admin/navbar' %>
<% end %>

<% content_for :left_sidebar do %>
  <%= render 'layouts/admin/left_sidebar' %>
<% end %>

<% content_for :breadcrumb_title do %>
  <%= render 'layouts/admin/breadcrumb_title' %>
<% end %>

<% content_for :right_sidebar do %>
  <%= render 'layouts/admin/right_sidebar' %>
<% end %>

<% content_for :footer do %>
  <%= render 'layouts/admin/footer' %>
<% end %>

<%= render 'layouts/propeller/application' %>